version: '3.3'
services:
  training-service:
    container_name: training-service
    build: ./training/.
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://training-db:5432/training
      SPRING_DATASOURCE_USERNAME: training-admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQL10Dialect
    depends_on:
      - training-db
    ports:
      - '8080:8080'
    expose:
      - '8080'
    networks:
      - backend

  training-db:
    container_name: training-db
    image: postgres:10
    restart: always
    environment:
      POSTGRES_DB: training
      POSTGRES_USER: training-admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - training-db:/var/lib/postgresql/data
    networks:
      - backend
volumes:
  training-db:
networks:
  backend: