spring:
  application:
    name: training
  liquibase:
    change-log: db/changelog/changelog-master.xml
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/training
    username: training-admin
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  servlet:
    multipart:
      max-file-size: 10MB

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka