spring:
  application:
    name: training
  liquibase:
    change-log: db/changelog/changelog-master.xml
    enabled: true
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka